version: "3.8"
services:
  redisapp:
    container_name: "redis"
    image: redis:6.2
    ports:
      - "8004:6379"
  
  webapi:
    container_name: "food-api"
    image: ghcr.io/mrkresnofatih/ghcr.io/mrkresnofatih/fav-food-api:v1.0.2
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FavoriteFoodApiRedisPort=6379
      - FavoriteFoodApiRedisHost=redis
    links:
      - redisapp
    depends_on:
      - redisapp